DROP TABLE IF EXISTS PREFIXsession_results;
DROP TABLE IF EXISTS PREFIXsessions;
DROP TABLE IF EXISTS PREFIXuser_machines;
DROP TABLE IF EXISTS PREFIXmachines;
DROP TABLE IF EXISTS PREFIXusers;
-- End
